
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Update these values with your new Supabase project credentials
const SUPABASE_URL = "https://swmoolbumenhwczvorln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3bW9vbGJ1bWVuaHdjenZvcmxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODM4NzksImV4cCI6MjA2MDA1OTg3OX0.IgrQKBhpgkIkWQdDXv5yzCbTSllXE1PTfBv5lGfQ0E8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
